name: Keeper – Mint Inflation
on:
  schedule:
    - cron:  '30 1 * * *'   # 01:30 UTC daily
  workflow_dispatch:

jobs:
  run-keeper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: npm ci --omit=dev
      - run: npx ts-node keeper/cronMintInflation.ts
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.KEEPER_PK }}
          REWARDS_DISTRIBUTOR: ${{ secrets.REWARDS_DISTRIBUTOR }}
