name: Adapter-TAO CI

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "asconfig.json"
      - "package.json"
      - "aigraph.yaml"
      - ".github/workflows/adapter-ci.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "asconfig.json"
      - "package.json"
      - "aigraph.yaml"
      - ".github/workflows/adapter-ci.yml"

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js & npm cache
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # 3️⃣ Install dependencies
      - run: npm ci

      # 4️⃣ Run AssemblyScript unit tests (as-pect)
      - run: npm test

      # 5️⃣ Compile mapping to WASM
      - run: npm run build

      # 6️⃣ Save artefact (optional): upload built WASM for downstream jobs
      - uses: actions/upload-artifact@v3
        with:
          name: adapter-tao-wasm
          path: build/adapter.wasm
