// SPDX-License-Identifier: MIT
// -----------------------------------------------------------------------------
// spyro-sdk-js ▸ contracts/governance.ts
// -----------------------------------------------------------------------------
// Thin Ethers v6 wrappers around Spyro Governor & Timelock contracts.
// These helpers keep the public SDK surface small while still exposing
// strongly‑typed methods for common governance actions. All heavy lifting
// (full ABIs, type mappings) is generated by TypeChain in
// `contracts/types/`, ...
